import { prisma } from '../../frameworks/prisma/index.js';
import { dateService, environmentConfigService, fileTypeMimeTypeService, gradeService, nodeFileService, nodeMailerEmailService, sanitizerService, uuidService, winstonLoggerService } from '../../services/index.js';
import { CloseNewSubmissionInteractor } from './closeNewSubmissionInteractor.js';
import { DownloadNewAssignmentMediumInteractor } from './downloadNewAssignmentMediumInteractor.js';
import { DownloadNewPartMediumInteractor } from './downloadNewPartMediumInteractor.js';
import { DownloadNewSubmissionFeedbackInteractor } from './downloadNewSubmissionFeedbackInteractor.js';
import { DownloadNewUploadSlotInteractor } from './downloadNewUploadSlotInteractor.js';
import { EraseNewSubmissionFeedbackInteractor } from './eraseNewSubmissionFeedbackInteractor.js';
import { GetNewAssignmentInteractor } from './getNewAssignmentInteractor.js';
import { GetNewSubmissionInteractor } from './getNewSubmissionInteractor.js';
import { ReturnNewSubmissionInteractor } from './returnNewSubmissionInteractor.js';
import { SaveNewTextBoxInteractor } from './saveNewTextBoxInteractor.js';
import { SaveNewUploadSlotInteractor } from './saveNewUploadSlotInteractor.js';
import { SaveTutorNoteInteractor } from './saveTutorNoteInteractor.js';
import { UploadNewSubmissionFeedbackInteractor } from './uploadNewSubmissionFeedbackInteractor.js';

export const getNewSubmissionInteractor = new GetNewSubmissionInteractor(prisma, uuidService, dateService, winstonLoggerService);
export const getNewAssignmentInteractor = new GetNewAssignmentInteractor(prisma, uuidService, dateService, winstonLoggerService);
export const uploadNewSubmissionFeedbackInteractor = new UploadNewSubmissionFeedbackInteractor(prisma, uuidService, nodeFileService, fileTypeMimeTypeService, sanitizerService, dateService, environmentConfigService, winstonLoggerService);
export const downloadNewSubmissionFeedbackInteractor = new DownloadNewSubmissionFeedbackInteractor(prisma, uuidService, nodeFileService, sanitizerService, environmentConfigService, winstonLoggerService);
export const eraseNewSubmissionFeedbackInteractor = new EraseNewSubmissionFeedbackInteractor(prisma, uuidService, nodeFileService, dateService, environmentConfigService, winstonLoggerService);
export const closeNewSubmissionInteractor = new CloseNewSubmissionInteractor(prisma, uuidService, nodeMailerEmailService, gradeService, sanitizerService, dateService, winstonLoggerService);
export const returnNewSubmissionInteractor = new ReturnNewSubmissionInteractor(prisma, uuidService, dateService, winstonLoggerService);
export const saveNewTextBoxInteractor = new SaveNewTextBoxInteractor(prisma, uuidService, dateService, winstonLoggerService);
export const saveNewUploadSlotInteractor = new SaveNewUploadSlotInteractor(prisma, uuidService, dateService, winstonLoggerService);
export const saveTutorNoteInteractor = new SaveTutorNoteInteractor(prisma, winstonLoggerService);
export const downloadNewAssignmentMediumInteractor = new DownloadNewAssignmentMediumInteractor(prisma, uuidService, nodeFileService, sanitizerService, environmentConfigService, winstonLoggerService);
export const downloadNewPartMediumInteractor = new DownloadNewPartMediumInteractor(prisma, uuidService, nodeFileService, sanitizerService, environmentConfigService, winstonLoggerService);
export const downloadNewUploadSlotInteractor = new DownloadNewUploadSlotInteractor(prisma, uuidService, nodeFileService, sanitizerService, environmentConfigService, winstonLoggerService);
