import { prisma } from '../../frameworks/prisma/index.js';
import { dateService, environmentConfigService, nodeFileService, sanitizerService, uuidService, winstonLoggerService } from '../../services/index.js';
import { CloseNewUnitInteractor } from './closeNewUnitInteractor.js';
import { DownloadNewAssignmentMediumInteractor } from './downloadNewAssignmentMediumInteractor.js';
import { DownloadNewPartMediumInteractor } from './downloadNewPartMediumInteractor.js';
import { DownloadNewUnitFeedbackInteractor } from './downloadNewUnitFeedbackInteractor.js';
import { DownloadNewUploadSlotInteractor } from './downloadNewUploadSlotInteractor.js';
import { EraseNewUnitFeedbackInteractor } from './eraseNewUnitFeedbackInteractor.js';
import { GetNewAssignmentInteractor } from './getNewAssignmentInteractor.js';
import { GetNewUnitInteractor } from './getNewUnitInteractor.js';
import { ReturnNewUnitInteractor } from './returnNewUnitInteractor.js';
import { SaveNewTextBoxInteractor } from './saveNewTextBoxInteractor.js';
import { SaveNewUploadSlotInteractor } from './saveNewUploadSlotInteractor.js';
import { UploadNewUnitFeedbackInteractor } from './uploadNewUnitFeedbackInteractor.js';

export const getNewUnitInteractor = new GetNewUnitInteractor(prisma, uuidService, winstonLoggerService);
export const getNewAssignmentInteractor = new GetNewAssignmentInteractor(prisma, uuidService, winstonLoggerService);
export const uploadNewUnitFeedbackInteractor = new UploadNewUnitFeedbackInteractor(prisma, uuidService, nodeFileService, environmentConfigService, winstonLoggerService);
export const downloadNewUnitFeedbackInteractor = new DownloadNewUnitFeedbackInteractor(prisma, uuidService, nodeFileService, sanitizerService, environmentConfigService, winstonLoggerService);
export const eraseNewUnitFeedbackInteractor = new EraseNewUnitFeedbackInteractor(prisma, uuidService, nodeFileService, environmentConfigService, winstonLoggerService);
export const closeNewUnitInteractor = new CloseNewUnitInteractor(prisma, uuidService, dateService, winstonLoggerService);
export const returnNewUnitInteractor = new ReturnNewUnitInteractor(prisma, uuidService, winstonLoggerService);
export const saveNewTextBoxInteractor = new SaveNewTextBoxInteractor(prisma, uuidService, winstonLoggerService);
export const saveNewUploadSlotInteractor = new SaveNewUploadSlotInteractor(prisma, uuidService, winstonLoggerService);
export const downloadNewAssignmentMediumInteractor = new DownloadNewAssignmentMediumInteractor(prisma, uuidService, nodeFileService, sanitizerService, environmentConfigService, winstonLoggerService);
export const downloadNewPartMediumInteractor = new DownloadNewPartMediumInteractor(prisma, uuidService, nodeFileService, sanitizerService, environmentConfigService, winstonLoggerService);
export const downloadNewUploadSlotInteractor = new DownloadNewUploadSlotInteractor(prisma, uuidService, nodeFileService, sanitizerService, environmentConfigService, winstonLoggerService);
