import { winston } from '../frameworks/winston/index.js';
import { privateKey, publicKey } from '../keys.js';
import { ZLibCompressionService } from './compression/zlibCompressionService.js';
import { EnvironmentConfigService } from './config/environmentConfigService.js';
import { NodeCryptoService } from './crypto/nodeCryptoService.js';
import { DateService } from './date/dateService.js';
import { NodemailerEmailService } from './email/nodemailerEmailService.js';
import { EmailValidatorService } from './emailValidator/emailValidatorService.js';
import { NodeFileService } from './file/nodeFileService.js';
import { GradeService } from './grade/gradeService.js';
import { AxiosHttpService } from './http/axiosHttpService.js';
import { IpaddrJSIPAddressService } from './ipaddress/ipaddrIPAddressService.js';
import { JWTService } from './jwt/jwtService.js';
import { WinstonLoggerService } from './logger/winstonLoggerService.js';
import { FileTypeMimeTypeService } from './mimeType/fileTypeMimeTypeService.js';
import { PasswordService } from './password/passwordService.js';
import { SanitizerService } from './sanitizer/sanitizerService.js';
import { FisherYatesShuffleService } from './shuffle/fisherYatesShuffleService.js';
import { StudentService } from './student/studentService.js';
import { TelephoneNumberService } from './telephoneNumber/telephoneNumberService.js';
import { ExtractZipUnzipService } from './unzip/extractZipUnzipService.js';
import { UUIDService } from './uuid/uuidService.js';

// service singletons
export const environmentConfigService = new EnvironmentConfigService();
const { email } = environmentConfigService.config;
export const nodeCryptoService = new NodeCryptoService();
export const nodeMailerEmailService = new NodemailerEmailService(email.host, email.port, email.user, email.pass, email.mode);
export const nodeFileService = new NodeFileService();
export const winstonLoggerService = new WinstonLoggerService(winston);
export const dateService = new DateService();
export const telephoneNumberService = new TelephoneNumberService();
export const passwordService = new PasswordService();
export const ipaddrJSIPAddressService = new IpaddrJSIPAddressService();
export const jwtService = new JWTService(privateKey, publicKey);
export const studentService = new StudentService();
export const gradeService = new GradeService();
export const zLibcompressionService = new ZLibCompressionService();
export const fisherYatesShuffleService = new FisherYatesShuffleService();
export const uuidService = new UUIDService();
export const sanitizerService = new SanitizerService();
export const axiosHttpService = new AxiosHttpService();
export const extractZipUnzipService = new ExtractZipUnzipService();
export const fileTypeMimeTypeService = new FileTypeMimeTypeService();
export const emailValidatorService = new EmailValidatorService();
