export type StudentDTO = {
  studentId: number;
  countryId: number;
  provinceId: number | null;
  studentTypeId: string;
  // passwordHash: string | null;
  // salt: string | null;
  // password: string | null;
  passwordChanged: boolean;
  sex: 'M' | 'F';
  firstName: string;
  lastName: string;
  numLogins: number;
  lastLogin: Date | null;
  expiry: Date | null;
  emailAddress: string | null;
  arrears: boolean;
  forumUsername: string | null;
  // forumPassword: string | null;
  // forumIV: Buffer | null;
  // forumPasswordNew: string | null;
  apiUsername: number | null;
  // apiPassword: string | null;
  // apiIV: Buffer | null;
  // apiPasswordNew: string | null;
  questionnaire: boolean;
  videoViewed: boolean;
  ajaxUploads: boolean;
  upgradeNotification: boolean;
  tutorNote: string | null;
  adminNote: string | null;
  entityVersion: number;
  created: Date;
  modified: Date;
};
