import { prisma } from '../../frameworks/prisma/index.js';
import { dateService, emailValidatorService, environmentConfigService, nodeFileService, nodeMailerEmailService, sanitizerService, uuidService, winstonLoggerService, zLibcompressionService } from '../../services/index.js';
import { DeleteMaterialCompletionInteractor } from './deleteMaterialCompletionInteractor.js';
import { DownloadMaterialImageInteractor } from './downloadMaterialImageInteractor.js';
import { DownloadNewAssignmentMediumInteractor } from './downloadNewAssignmentMediumInteractor.js';
import { DownloadNewPartMediumInteractor } from './downloadNewPartMediumInteractor.js';
import { DownloadNewSubmissionFeedbackInteractor } from './downloadNewSubmissionFeedbackInteractor.js';
import { DownloadNewUploadSlotInteractor } from './downloadNewUploadSlotInteractor.js';
import { EraseNewUploadSlotInteractor } from './eraseNewUploadSlotInteractor.js';
import { GetEnrollmentInteractor } from './getEnrollment.js';
import { GetNewAssignmentInteractor } from './getNewAssignmentInteractor.js';
import { GetNewSubmissionInteractor } from './getNewSubmissionInteractor.js';
import { GetStudentInteractor } from './getStudentInteractor.js';
import { GetT2202ReceiptsInteractor } from './getT2202Receipts.js';
import { GetVideoInteractor } from './getVideoInteractor.js';
import { InitializeNextNewSubmissionInteractor } from './initializeNextNewSubmissionInteractor.js';
import { InsertMaterialCompletionInteractor } from './insertMaterialCompletionInteractor.js';
import { LessonGuardInteractor } from './lessonGuardInteractor.js';
import { SaveNewTextBoxTextInteractor } from './saveNewTextBoxTextInteractor.js';
import { SkipNewSubmissionInteractor } from './skipNewSubmissionInteractor.js';
import { SubmitNewSubmissionInteractor } from './submitNewSubmissionInteractor.js';
import { UpdateEmailAddressInteractor } from './updateEmailAddressInteractor.js';
import { UpdateNewSubmissionResponseProgressInteractor } from './updateNewSubmissionResponseProgressInteractor.js';
import { UploadNewUploadSlotInteractor } from './uploadNewUploadSlotInteractor.js';

// use-case interactor singletons
export const lessonGuardInteractor = new LessonGuardInteractor(prisma, uuidService, winstonLoggerService);

export const getStudentInteractor = new GetStudentInteractor(prisma, uuidService, dateService, winstonLoggerService);
export const getNewSubmissionInteractor = new GetNewSubmissionInteractor(prisma, uuidService, dateService, winstonLoggerService);
export const getNewAssignmentInteractor = new GetNewAssignmentInteractor(prisma, uuidService, dateService, winstonLoggerService);
export const getEnrollmentInteractor = new GetEnrollmentInteractor(prisma, uuidService, nodeFileService, dateService, environmentConfigService, winstonLoggerService);
export const saveNewTextBoxTextInteractor = new SaveNewTextBoxTextInteractor(prisma, uuidService, dateService, winstonLoggerService);
export const uploadNewUploadSlotInteractor = new UploadNewUploadSlotInteractor(prisma, uuidService, nodeFileService, zLibcompressionService, sanitizerService, dateService, environmentConfigService, winstonLoggerService);
export const eraseNewUploadSlotInteractor = new EraseNewUploadSlotInteractor(prisma, uuidService, nodeFileService, dateService, environmentConfigService, winstonLoggerService);
export const downloadNewUploadSlotInteractor = new DownloadNewUploadSlotInteractor(prisma, uuidService, nodeFileService, sanitizerService, environmentConfigService, winstonLoggerService);
export const submitNewSubmissionInteractor = new SubmitNewSubmissionInteractor(prisma, uuidService, nodeMailerEmailService, dateService, winstonLoggerService);
export const skipNewSubmissionInteractor = new SkipNewSubmissionInteractor(prisma, uuidService, dateService, winstonLoggerService);
export const initializeNextNewSubmissionInteractor = new InitializeNextNewSubmissionInteractor(prisma, uuidService, dateService, winstonLoggerService);
export const downloadNewAssignmentMediumInteractor = new DownloadNewAssignmentMediumInteractor(prisma, uuidService, nodeFileService, sanitizerService, environmentConfigService, winstonLoggerService);
export const downloadNewPartMediumInteractor = new DownloadNewPartMediumInteractor(prisma, uuidService, nodeFileService, sanitizerService, environmentConfigService, winstonLoggerService);
export const updateEmailAddressInteractor = new UpdateEmailAddressInteractor(prisma, emailValidatorService, dateService, winstonLoggerService);
export const getT2202ReceiptsInteractor = new GetT2202ReceiptsInteractor(prisma, dateService, winstonLoggerService);
export const downloadMaterialImageInteractor = new DownloadMaterialImageInteractor(prisma, uuidService, nodeFileService, sanitizerService, environmentConfigService, winstonLoggerService);
export const insertMaterialCompletionInteractor = new InsertMaterialCompletionInteractor(prisma, uuidService, winstonLoggerService);
export const deleteMaterialCompletionInteractor = new DeleteMaterialCompletionInteractor(prisma, uuidService, winstonLoggerService);
export const getVideoInteractor = new GetVideoInteractor(prisma, uuidService, winstonLoggerService);
export const downloadNewSubmissionFeedbackInteractor = new DownloadNewSubmissionFeedbackInteractor(prisma, uuidService, nodeFileService, environmentConfigService, winstonLoggerService);
export const updateNewSubmissionResponseProgressInteractor = new UpdateNewSubmissionResponseProgressInteractor(prisma, uuidService, dateService, winstonLoggerService);
